name: messaging_service
description: Library for creating a messaging service for different kind of messages received from FirebaseMessaging
version: 1.4.0
homepage: https://github.com/dumabg/messaging_service.git

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  firebase_core: any
  firebase_messaging: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.19.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
